
# Default configuration values for MusicRenamer

DEFAULT_BANNED_WORDS = [
    "Version",
    "Ver.",
    "Bonus Track",
    "Free Download",
    "Remaster",
    "Remastered",
    "Music Video",
    "Lyric Video",
    "Lyrics Video",
    "Dynamic Art Video",
    "Visualizer",
    "Art Track",
    "Officiell Video",
    "Official Visual",
    "Official Audio",
    "Official Music",
    "Radio Edit",
    "HD",
    "HQ",
    "4K",
    "Official",
    "Offical",
    "Audio",
    "Video",
    "Full EP Stream",
    "Official Guitar Playthrough",
    "Official Video Short",
    "Official Video",
    "Teaser",
    "Extended",
    "US Version",
    "Performance Video",
    "Concept Trailer",
    "LyricVideo",
    "Lyric Video",
    "Music Video",
    "- Music Video",
    "Official Lyric Video",
    "Official Lyricvideo",
    "Visualiser",
    "(Short)",
    "( Short)",
    "Official",
    "(Official Track Premiere)"
]

DEFAULT_TAG_MAPPINGS = {
    "(acoustic|akustik)": "[Acoustic]",
    "acapella": "[Acapella]",
    "instrumental": "[Instrumental]",
    "piano": "[Piano]",
    "live": "[Live]",
    "vocal cover": "[Vocal Cover]",
    "demo": "[Demo]",
    "alternative version": "[Alternative Remix]",
    "radio version": "[Radio Remix]",
    "radio edit": "[Radio Remix]",
    "unplugged": "[Unplugged]"
}
